svg_icons:
  default: "palette|glass-cheers"
  type: "list"
  list_type: "compact"
welcome:
  default: ""
  type: "string"
subtitle:
  default: ""
  type: "string"
first_icon:
  default: "info-circle"
  type: "string"
first_label:
  default: ""
  type: "string"
first_link:
  default: "/tags"
  type: "string"
second_icon:
  default: "tags"
  type: "string"
second_label:
  default: ""
  type: "string"
second_link:
  default: "/tags"
  type: "string"
third_icon:
  default: "glass-cheers"
  type: "string"
third_label:
  default: ""
  type: "string"
third_link:
  default: ""


